abhiyaan/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
    path('days/', include("days.urls")),
    path('departmentalfests/', include("departmentalfests.urls")),
    path('maineventsdayone/', include("maineventsdayone.urls")),
    path('maineventsdaytwo/', include("maineventsdaytwo.urls")),
    path('maineventsdaythree/', include("maineventsdaythree.urls")),
    path('sports/', include("sports.urls")),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

days/urls.py
from django.urls import path
from . import views
app_name="days"
urlpatterns=[
    path("", views.index, name="index"),
    path("<str:day>", views.day, name="day"),
    path("<str:day>/<str:event>", views.event, name="event"),
]

departmentalfests/urls.py
from django.urls import path
from . import views
app_name="departmentalfests"
urlpatterns=[
    path("", views.index, name="index"),
    path("<str:department>", views.department, name="department"),
    path("<str:department>/<str:event>", views.event, name="event"),
]

home/urls.py
from django.urls import path
from . import views
app_name="home"
urlpatterns=[
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("about", views.about, name="about")
]

sports/urls.py
from django.urls import path
from . import views
app_name="sports"
urlpatterns=[
    path("", views.index, name="index"),
    path("<str:sport>", views.sport, name="sport")
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "home/index.html", {
        "days": ["Clan", "Corporate", "Traditional"],
        "departmentalfests": ["CSE", "IT", "EXTC", "ME", "CE"],
        "sports":["Kabaddi", "Kho-Kho", "Cricket", "Batminton"]
    })

def search(request):
    if request.method=="POST":
        nq=request.POST['q']
        print(nq)
        # Now we an process this querry as to search in our database and show results
    return render(request, "home/index.html", {
        "days": ["Clan", "Corporate", "Traditional"],
        "departmentalfests": ["CSE", "IT", "EXTC", "ME", "CE"],
        "sports":["Kabaddi", "Kho-Kho", "Cricket", "Batminton"]
    })

def about(request):
    return render(request, "home/about.html", {
        "days": ["Clan", "Corporate", "Traditional"],
        "departmentalfests": ["CSE", "IT", "EXTC", "ME", "CE"],
        "sports":["Kabaddi", "Kho-Kho", "Cricket", "Batminton"]
    })

home/templates/home/about.html
{% extends "home/layout.html" %}
{% block title %}
About Us
{% endblock %}
{% block body %}
<h1>ABOUT US PAGE</h1>
{% endblock %}

home/templates/home/event.html
{% extends "home/layout.html" %}
{% block title %}
{{ event.name|safe }}
{% endblock %}
{% block body %}
<div class="container">
    <div class="card m-1">
        <h1 class="card-header text-center font-weight-bold">{{ event.name|upper|safe }}</h1>
        <div class="card-body img-thumbnail">
            <img class="card-img-top" src="{{ event.image.url }}" alt="Card image cap">
            <hr>
            <h5 class="card-title text-center font-weight-bold m-2">DESCRIPTION</h5>
            <hr>
            <p>{{ event.description|safe }}</p>
            <hr>
            <h5 class="card-title text-center font-weight-bold m-2">RULES AND REGULATIONS</h5>
            <hr>
            <p>{{ event.rules|safe }}</p>
        </div>
    </div>
    <div class="card m-1" id="register">
        <div class="card-header">
            <h2 class="text-center font-weight-bold card-title">REGISTER</h2>
        </div>
        <div class="card-body">
            {{ event.registrationform|safe }}
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/index.html
{% extends "home/layout.html" %}
{% block title %}
Abhiyaan
{% endblock title %}
{% block body %}
<div class="jumbotron">
    <h1>ABHIYAAN HOME PAGE</h1>
    <p>HELLO USER</p>
</div>
{% endblock body %}

home/templates/home/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title %}
      {% endblock title %}      
    </title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'home/styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/8bb574b8c0.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>
<body>    
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Abhiyaan</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link font-weight-bold m-1" href="/">Home</a>
            </li>
          
            <li>
              <div class="btn-group m-1">
                <a href="{% url 'days:index' %}" class="btn btn-secondary">Days</a>
                <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu">
                  {% for aday in day %}
                  <a class="dropdown-item" href="{% url 'days:day' aday.name %}">{{ aday.name }}</a>
                  {% endfor %}
                </div>
              </div>
            </li>
            <li>
              <div class="btn-group m-1">
                <a href="{% url 'departmentalfests:index' %}" class="btn btn-secondary">Departmental Fests</a>
                <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu">
                  {% for department in departments %}
                  <a class="dropdown-item" href="{% url 'departmentalfests:department' department.name %}">{{ department.name }}</a>
                  {% endfor %}
                </div>
              </div>
            </li>
            <!--  -->
            <li>
              <div class="btn-group m-1">
                <a href="{% url 'sports:index' %}" class="btn btn-secondary">Main Day Events</a>
                <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href=#>Day 1</a>
                  <a class="dropdown-item" href=#>Day 2</a>
                  <a class="dropdown-item" href=#>Day 3</a>
                </div>
              </div>
            </li>
            <!--  -->
            <li>
              <div class="btn-group m-1">
                <a href="{% url 'sports:index' %}" class="btn btn-secondary">Sports</a>
                <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu">
                  {% for sport in sports %}
                  <a class="dropdown-item" href="{% url 'sports:sport' sport %}">{{ sport }}</a>
                  {% endfor %}
                </div>
              </div>
            </li>
          </ul>
          <form method="post" action="{% url 'home:search' %}" class="form-inline my-2 my-lg-0">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
    </nav>
    {% block body %}
    {% endblock body %}
    <!-- BOTTOM NAVBAR -->
    <nav class="navbar navbar-light bg-light">
      <footer class="page-footer font-small mdb-color pt-4">
        <!-- Footer Links -->
        <div class="container text-center text-md-left">  
          <!-- Footer links -->
          <div class="row text-center text-md-left mt-3 pb-3">  
            <!-- Grid column -->
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">What is Abhiyaan?</h6>
              <p>It is the annual festival of our college wherein we do all that can be described as entertainment.It has a footall of over 3K+ students from 6 departments of BVCOENM. It is a wholesome experience of arts culture and unity in all differrent forms.</p>
            </div>
            <!-- Grid column -->  
            <hr class="w-100 clearfix d-md-none">  
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Direct Links</h6>
              <p>
                <a href="#!">Blog</a>
              </p>
              <p>
                <a href="#!">Zeal Magazine</a>
              </p>
              <p>
                <a href="#!">Sigma</a>
              </p>
              <p>
                <a href="#!">BVCOENM</a>
              </p>
            </div>
            <!-- Grid column -->  
            <hr class="w-100 clearfix d-md-none">  
            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Useful links</h6>
              <p>
                <a href="{% url 'days:index' %}">Days</a>
              </p>
              <p>
                <a href="{% url 'departmentalfests:index' %}">Departmental Fests</a>
              </p>
              <p>
                <a href="#!">Main Day Events</a>
              </p>
              <p>
                <a href="{% url 'sports:index' %}">Sports</a>
              </p>
            </div>  
            <!-- Grid column -->
            <hr class="w-100 clearfix d-md-none">  
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
              <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
              <p>
                <i class="fas fa-home mr-3"></i>Sector-7, CBD, Belapur, Near Kharghar Railway Station, Navi Mumbai-400614</p>
              <p>
                <i class="fas fa-envelope mr-3"></i>abhiyaanbvcoenm2020@gmail.com</p>
              <p>
                <i class="fas fa-phone mr-3"></i>+91 -022-27572140</p>
              <p>
                <i class="fas fa-print mr-3"></i>+91 -022-27571074</p>
            </div>
            <!-- Grid column -->  
          </div>
          <!-- Footer links -->  
          <hr>  
          </div>
          <!-- Grid row -->
        
        <!-- Footer Links -->
      </footer>
      <!-- Footer -->
    </nav>
    <!-- BOTTOM NAVBAR -->
</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</html>