abhiyaan/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
    path('days/', include("days.urls")),
    path('departmentalfests/', include("departmentalfests.urls")),
    path('maineventsdayone/', include("maineventsdayone.urls")),
    path('maineventsdaytwo/', include("maineventsdaytwo.urls")),
    path('maineventsdaythree/', include("maineventsdaythree.urls")),
    path('sports/', include("sports.urls")),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

days/urls.py
from django.urls import path
from . import views
app_name="days"
urlpatterns=[
    path("", views.index, name="index"),
    path("<str:day>", views.day, name="day"),
    path("<str:day>/<str:event>", views.event, name="event"),
]

departmentalfests/urls.py
from django.urls import path
from . import views
app_name="departmentalfests"
urlpatterns=[
    path("", views.index, name="index"),
    path("<str:department>", views.department, name="department"),
    path("<str:department>/<str:event>", views.event, name="event"),
]

departmentalfests/models.py
from django.db import models
import re
#-----------------------------
def remove_html_tags(text):
    """Remove html tags from a string"""
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)
#-----------------------------
# Create your models here.
class Event(models.Model):
    name           =  models.CharField(max_length=1000)
    image          =  models.ImageField(upload_to='images', blank=True)
    description    =  models.TextField(blank=True)
    eventhead      =  models.CharField(max_length=1000)
    rules          =  models.TextField(blank=True)
    registrationform= models.CharField(max_length=1000, blank=True)


    def __str__(self):
        return remove_html_tags(self.name)
    
class Department(models.Model):
    name        =   models.CharField(max_length=1000)
    description =   models.TextField(blank=True)
    imageOne    =   models.ImageField(blank=True)
    imageTwo    =   models.ImageField(blank=True)
    imageThree  =   models.ImageField(blank=True)
    events      =   models.ManyToManyField(Event, related_name="eventofdepartment", blank=True)

    def __str__(self):
        return remove_html_tags(self.name)

class DepartmentalFest(models.Model):
    imageOne    =   models.ImageField(blank=True)
    imageTwo    =   models.ImageField(blank=True)
    imageThree  =   models.ImageField(blank=True)
    description =   models.TextField(blank=True)
    department  =   models.ManyToManyField(Department, related_name="departmentofdepartmentalfests", blank=True)

    def __str__(self):
        return "Departmentalfest"

departmentalfests/views.py
from django.shortcuts import render
from days.models import *
from .models import *

#---------------------------------------------------

#---------------------------------------------------

# Create your views here.
def index(request):
    days=Days.objects.all()[0]
    day=Day.objects.all()
    departmentalfests=DepartmentalFest.objects.all()[0]
    departments=Department.objects.all()
    events=Event.objects.all()
    return render(request, "departmentalfests/index.html", {
        "days": days,
        "day":day,
        "departments": departments,
        "departmentalfests": departmentalfests,
        "sports":["Kabaddi", "Kho-Kho", "Cricket", "Batminton"]
    }) 

def department(request, department):
    days=Days.objects.all()[0]
    day=Day.objects.all()
    departmentalfests=DepartmentalFest.objects.all()[0]
    departments=Department.objects.all()
    events=Event.objects.all()
    tdepartment=Department.objects.get(name=department)
    return render(request, "departmentalfests/department.html", {
        "days": days,
        "day": day,
        "departments": departments,
        "tdepartment": tdepartment,
        "events": events,
        "departmentalfests": departmentalfests,
        "sports":["Kabaddi", "Kho-Kho", "Cricket", "Batminton"]
    })

def event(request, department, event):
    tdepartment=Department.objects.get(name=department)
    tevent=Department.objects.get(name=department).events.get(name=event)
    days=Days.objects.all()[0]
    day=Day.objects.all()
    departmentalfests=DepartmentalFest.objects.all()[0]
    departments=Department.objects.all()
    events=Event.objects.all()

    return render(request, "home/event.html", {
        "days": days,
        "day": day,
        "events": events,
        "event": tevent,
        "department": departments,
        "tdepartment": tdepartment,
        "sports":["Kabaddi", "Kho-Kho", "Cricket", "Batminton"]
    })

departmentalfests/templates/departmentalfests/department.html
{% extends "home/layout.html" %}
{% block title %}
{{ tdepartment.name|safe }}
{% endblock %}
{% block body %}
<div class="jumbotron d-flex justify-content-center m-0 p-3">
    <h1 class="display-2 font-weight-bold">{{ tdepartment.name|upper|safe }}</h1>
</div>
<!--  -->
<div class="container">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{{ tdepartment.imageOne.url }}" class="d-block daysCarousel w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{{ tdepartment.imageTwo.url }}" class="d-block daysCarousel w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{{ tdepartment.imageThree.url }}" class="d-block daysCarousel w-100" alt="...">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<div class="jumbotron m-1 p-3 text-center">
  <h1>What is {{ tdepartment.name|safe }} Departmental Fest ?</h1>
  <p>{{ tdepartment.description|safe }}</p>
</div>
<!--  -->
<div class="container">
    <div class="row">
        {% for event in tdepartment.events.all %}
            <div class="col">
                <div class="card m-2">
                    <div class="row no-gutters">
                      <div class="col-md-4">
                        <img class="img-thumbnail w-100 h-100" src="{{ event.image.url }}" class="card-img" alt="...">
                      </div>
                      <div class="col-md-8">
                        <div class="card-body">
                          <a href="{% url 'departmentalfests:event' tdepartment.name event.name %}"><h5 class="card-title">{{ event.name|safe }}</h5></a>
                          <p class="card-text">{{ event.description|truncatewords:700|safe }}</p>
                          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                        </div>
                      </div>
                    </div>
                  </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

departmentalfests/templates/departmentalfests/index.html
{% extends "home/layout.html" %}
{% block title %}
Departmental Fests
{% endblock title %}
{% block body %}
<div class="jumbotron d-flex justify-content-center m-1 p-3">
    <h1 class="display-2 font-weight-bold">DEPARTMENTAL FESTS</h1>
</div>
<div class="container">
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active m-1 img-thumbnail img-responsive">
            <img class="daysCarousel" src="{{ departmentalfests.imageOne.url }}" class="d-block w-100 img-fluid" alt="...">
          </div>
          <div class="carousel-item m-1 img-thumbnail img-responsive">
            <img class="daysCarousel" src="{{ departmentalfests.imageTwo.url }}" class="d-block w-100 img-fluid" alt="...">
          </div>
          <div class="carousel-item m-1 img-thumbnail img-responsive">
            <img class="daysCarousel" src="{{ departmentalfests.imageThree.url }}" class="d-block w-100 img-fluid" alt="...">
          </div>
        </div>
      </div>
</div>
<div class="container p-4 m-0">
    <h1 class="text-center">What Are Departmental Fest? </h1>
    <p>{{ departmentalfests.description|safe }}</p>
</div>
<div class="card m-1">
    <h1 class="card-header text-center font-weight-bold">Departments</h1>
    <div class="card-body">
        <div class="row">
            {% for department in departments %}
            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                <div class="card text-center img-thumbnail m-1" style="width: 30rem;">
                    <img src="{{ department.imageOne.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <a href="{% url 'departmentalfests:department' department.name %}"><h5 class="card-title">{{ department.name|safe }}</h5></a>
                      <p class="card-text">{{ department.description|truncatewords:20|safe }}</p>
                      <a href="{% url 'departmentalfests:department' department.name %}" class="btn btn-primary m-2">All Events</a>
                    </div>
                  </div>
            </div>
            {% endfor %}
        </div>
    </div>
  </div>
{% endblock body %}