abhiyaan/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
    path('days/', include("days.urls")),
    path('departmentalfests/', include("departmentalfests.urls")),
    path('maineventsdayone/', include("maineventsdayone.urls")),
    path('maineventsdaytwo/', include("maineventsdaytwo.urls")),
    path('maineventsdaythree/', include("maineventsdaythree.urls")),
    path('sports/', include("sports.urls")),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

days/urls.py
from django.urls import path
from . import views
app_name="days"
urlpatterns=[
    path("", views.index, name="index"),
    path("<str:day>", views.day, name="day"),
    path("<str:day>/<str:event>", views.event, name="event"),
]

days/models.py
from django.db import models
import re
# Create your models here.

#-----------------------------
def remove_html_tags(text):
    """Remove html tags from a string"""
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)
#-----------------------------
class Event(models.Model):
    name           =  models.CharField(max_length=1000)
    image          =  models.ImageField(upload_to='images', blank=True)
    description    =  models.TextField(blank=True)
    eventhead      =  models.CharField(max_length=1000)
    rules          =  models.TextField(blank=True)    
    registrationform= models.CharField(max_length=1000, blank=True)

    def __str__(self):
        return remove_html_tags(self.name)

class Day(models.Model):
    name        =  models.CharField(max_length=1000)
    imageOne    =  models.ImageField(upload_to='images', blank=True)
    imageTwo    =  models.ImageField(upload_to='images', blank=True)
    imageThree  =  models.ImageField(upload_to='images', blank=True)
    description =  models.TextField(blank=True)
    events      =  models.ManyToManyField(Event, blank=True, related_name="eventsofday")

    def __str__(self):
        return remove_html_tags(self.name)
    

class Days(models.Model):
    imageOne   =  models.ImageField(upload_to='images', blank=True)
    imageTwo   =  models.ImageField(upload_to='images', blank=True)
    imageThree =  models.ImageField(upload_to='images', blank=True)
    description=  models.TextField(blank=True)
    day        =  models.ManyToManyField(Day, blank=True, related_name="dayofdays")

    def __str__(self):
        return 'Days'

days/views.py
from django.shortcuts import render
from .models import *
from departmentalfests.models import *
#-----------------------------------------------------------
departmentalfests=DepartmentalFest.objects.all()
#-----------------------------------------------------------
# Create your views here.
def index(request):
    days=Days.objects.all()[0]
    day=Day.objects.all()
    departments=Department.objects.all()

    return render(request, "days/index.html", {
        "days": days,
        "day":day,
        "departments": departments,
        "sports":["Kabaddi", "Kho-Kho", "Cricket", "Batminton"]
    })

def day(request, day):
    oday=Day.objects.all()
    days=Days.objects.all()
    tday=Day.objects.get(name=day)
    events=Event.objects.all()
    departments=Department.objects.all()

    return render(request, "days/day.html", {
        "days": days,
        "day": oday,
        "tday":tday,
        "events": events,
        "departments": departments,
        "sports":["Kabaddi", "Kho-Kho", "Cricket", "Batminton"]
    })

def event(request, day, event):
    departments=Department.objects.all()
    days=Days.objects.all()[0]
    oday=Day.objects.all()
    tday=Day.objects.get(name=day)
    events=Event.objects.all()
    tevent=Day.objects.get(name=day).events.get(name=event)
    
    return render(request, "home/event.html", {
        "days": days,
        "day": oday,
        "tday": tday,
        "events": events,
        "event": tevent,
        "department": departments,
        "sports":["Kabaddi", "Kho-Kho", "Cricket", "Batminton"]
    })

days/templates/days/day.html
{% extends "home/layout.html" %}
{% block title %}
{{ tday.name|safe }}
{% endblock %}
{% block body %}
<div class="jumbotron d-flex justify-content-center m-0 p-3">
    <h1 class="display-2 font-weight-bold">{{ tday.name|upper|safe }}</h1>
</div>
<div class="container">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" >
      <div class="carousel-item active img-thumbnail">
        <img src="{{ tday.imageOne.url }}" class="d-block daysCarousel w-100" alt="...">
      </div>
      <div class="carousel-item img-thumbnail">
        <img src="{{ tday.imageTwo.url }}" class="d-block daysCarousel w-100" alt="...">
      </div>
      <div class="carousel-item img-thumbnail">
        <img src="{{ tday.imageThree.url }}" class="d-block daysCarousel w-100" alt="...">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<!--  -->
<div class="m-1 p-3 text-center">
  <h1>What is {{ tday.name|safe }}?</h1>
  <p>{{ tday.description|safe }}</p>
</div>
<div class="container">
    <!-- <div class="jumbotron d-flex justify-content-center p-1 m-1">
        <h1 class="display-1">Events</h1>
    </div> -->
    <div class="card">
      <div class="card-header">
        <h4 class="card-title font-weight-bold text-center">EVENTS</h4>
      </div>
      <div class="card-body">
        <div class="row">
        {% for event in tday.events.all %}
          <div class="col m-2">
            <div class="card img-thumbnail" >
              <img class="card-img-top daysCarousel" src="{{ event.image.url }}" alt="Card image cap">
              <div class="card-body">
                <a href="{% url 'days:event' tday.name event.name %}"><h5 class="card-title font-weight-bold">{{ event.name|safe }}</h5></a>
                <p class="card-text">{{ event.description|truncatewords:250|safe }}</p>
                <a href="{% url 'days:event' tday.name event.name %}#register" class="btn btn-primary">Register</a>
              </div>
            </div>
          </div>            
        {% endfor %}
        </div>
      </div>
    </div>
    
</div>

{% endblock %}

days/templates/days/index.html
{% extends "home/layout.html" %}
{% block title %}
Days
{% endblock title %}
{% block body %}
<div class="jumbotron d-flex justify-content-center m-0 p-3">
  <h1 class="display-2 font-weight-bold">DAYS</h1>
</div>
<div class="container">
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active img-thumbnail img-responsive">
              <img class="daysCarousel" src="{{ days.imageOne.url }}" class="d-block w-100 img-fluid" alt="...">
          </div>
          <div class="carousel-item img-thumbnail img-responsive">
            <img class="daysCarousel" src="{{ days.imageTwo.url }}" class="d-block w-100 img-fluid" alt="...">
          </div>
          <div class="carousel-item img-thumbnail img-responsive">
            <img class="daysCarousel" src="{{ days.imageThree.url }}" class="d-block w-100 img-fluid" alt="...">
          </div>
        </div>
      </div>
</div>
<div class="p-4 container text-centre">
  <h1 class="font-weight-bold text-center">A FEST LIKE NEVER BEFORE!</h1>
  <p class="text-center ">{{ days.description|safe }}</p>
</div>
<div class="container">
  <div class="row m-1">
    {% for aday in day %}
    <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12">
      <div class="card img-thumbnail" style="width: 18rem;">
        <img class="card-img-top" src="{{ aday.imageOne.url }}" alt="Card image cap">
        <div class="card-body">
          <a href="{% url 'days:day' aday %}"><h5 class="card-title">{{ aday.name|safe }}</h5></a>
          <p class="card-text">{{ aday.description|truncatewords:30|safe }}<a href="{% url 'days:day' aday %}">...</h5></a></p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock body %}